# Configure Using Gemfile
# gem 'pg'

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: practice_api_development

test:
  <<: *default
  database: practice_api_test

production:
  <<: *default
  database: practice_api_production
  username: practice_api
  password: <%= ENV['PRACTICE_API_DATABASE_PASSWORD'] %>
